- name: "WSL2 Ubuntu Setup"
  hosts: "localhost"
  gather_facts: true
  become: true

  pre_tasks:
    - name: "Package update"
      include_tasks: "tasks/update.yaml"

  roles:
    - name: "Setup system configuration role"
      role: "system_setup"

    - name: "Setup development environment"
      role: "dev_setup"
      become: false
