---
- name: "WSL2 Ubuntu Setup"
  hosts: "localhost"
  gather_facts: true
  become: true

#  pre_tasks:
#    - name: "Install modules required for provisioning"
#      ansible.builtin.include_tasks: "tasks/install_ansible_required_module.yaml"
#
#    - name: "Package update"
#      ansible.builtin.include_tasks: "tasks/package_update.yaml"

  roles:
    - name: "System configuration roles"
      role: "system_configuration"
#
#    - name: "Development environment building role"
#      role: "dev_setup"
#      become: false
#
#    - name: "Routine provisioning configuration roles by ansible"
#      role: "ansible_configure"
