---
- name: "WSL2 Ubuntu Setup"
  hosts: "localhost"
  gather_facts: true
  become: true

  pre_tasks:
    - name: "Setup ansible"
      ansible.builtin.include_tasks: "tasks/requirement_ansible_module.yaml"
    - name: "Package update"
      ansible.builtin.include_tasks: "tasks/update.yaml"

  roles:
    - name: "Setup system configuration role"
      role: "system_setup"

    - name: "Setup development environment"
      role: "dev_setup"
      become: false

    - name: "Setup ansible configure"
      role: "ansible_configure"
