---
- name: "Download flux2 cli install script"
  ansible.builtin.get_url:
    url: "https://fluxcd.io/install.sh"
    dest: "{{ tmp_dir }}/flux2-cli.sh"
    owner: "root"
    group: "root"
    mode: "0755"

- name: "Execute flux2 cli install script"
  ansible.builtin.command:
    cmd: "bash {{ tmp_dir }}/flux2-cli.sh"

- name: "Remove install script"
  ansible.builtin.file:
    path: "{{ tmp_dir }}/flux2-cli.sh"
    state: "absent"
