---
- name: "Install legacy versions for each language"
  block:
    - name: "Get installed versions for {{ item.plugin_name }}"
      ansible.builtin.command:
        cmd: "{{ asdf_bin }} list {{ item.plugin_name }}"
      register: "installed_versions"
      changed_when: false

    - name: "Install legacy versions of {{ item.plugin_name }}"
      ansible.builtin.command:
        cmd: "{{ asdf_bin }} install {{ item.plugin_name }} {{ item_version }}"
      loop: "{{ item.versions }}"
      loop_control:
        loop_var: "item_version"
      when: "item not in installed_versions.stdout.splitlines()"
      register: "install_result"
      changed_when: "'is already installed' not in install_result.stdout"
