---
- name: "Setup asdf"
  ansible.builtin.include_tasks: "asdf.yaml"

- name: "Setup golang environments"
  ansible.builtin.include_tasks: "setup-go.yaml"

- name: "Setup nodejs environments"
  ansible.builtin.include_tasks: "setup-node.yaml"

- name: "Setup kubernetes operation environments"
  ansible.builtin.include_tasks: "setup-kubernetes.yaml"

- name: "Setup VCS"
  ansible.builtin.include_tasks: "setup-vcs.yaml"
