---
- name: "Install packages required for golang system development"
  ansible.builtin.apt:
    name:
      - "golang-go"
      - "qemu-system-arm"       # Required for binary builds for arm
      - "g++-aarch64-linux-gnu" # Required for binary builds for arm
    state: "present"

- name: "Add golang to path"
  ansible.builtin.blockinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    block: |
      # go setup
      export PATH="$({{ go_bin }} env GOPATH)/bin:$PATH"
    marker: "# {mark} GO SETUP"
    create: true
    mode: "0644"

- name: "Install golang modules"
  ansible.builtin.command:
    cmd: "{{ go_bin }} install {{ item }}"
  loop:
    - "mvdan.cc/gofumpt@latest"
    - "github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest"
