---
- name: "Update npm module"
  ansible.builtin.command:
    cmd: "{{ asdf_shims }}/npm install -g npm@latest"
  register: "npm_update_output"
  changed_when: "'up to date' not in npm_update_output.stdout"
