---
- name: "Remove snap packages tasks"
  ansible.builtin.include_tasks: "remove-snap-packages.yaml"

- name: "Default requirements package management"
  ansible.builtin.include_tasks: "requirements-package.yaml"

- name: "Setup Oh-my-bash"
  ansible.builtin.include_tasks: "oh-my-bash.yaml"

- name: "Setup system configuration"
  ansible.builtin.include_tasks: "system-configure.yaml"
