---
- name: "Check if Oh-my-bash is already installed"
  stat:
    path: "/usr/local/share/oh-my-bash"
  register: "omb_dir"

- name: "Get Oh-my-bash installation script"
  get_url:
    url: "https://raw.github.com/ohmybash/oh-my-bash/master/tools/install.sh"
    dest: "{{ tmp_dir }}/oh_my_bash_install.sh"
    mode: "0755"
  when: "not omb_dir.stat.exists"

- name: "Install Oh-my-bash"
  command:
    cmd: "{{ tmp_dir }}/oh_my_bash_install.sh --prefix=/usr/local"
  changed_when: true
  when: "not omb_dir.stat.exists"

- name: "Ensure oh-my-bash is sourced in /etc/bash.bashrc"
  lineinfile:
    path: "/etc/bash.bashrc"
    line: "source /usr/local/share/oh-my-bash/bashrc"
    state: "present"

- name: "Ensure OSH_THEME is set to powerline-icon"
  replace:
    path: "/usr/local/share/oh-my-bash/bashrc"
    regexp: '^OSH_THEME="font"$'
    replace: 'OSH_THEME="powerline-icon"'
