---
- name: "Get list of packages"
  ansible.builtin.package_facts:
    manager: "auto"

- name: "Remove list of snap packages"
  when: "'snapd' in ansible_facts.packages"
  block:
    - name: "Increment the retry count"
      ansible.builtin.set_fact:
        retry_count: "{{ 0 if retry_count is undefined else retry_count | int + 1 }}"

    - name: "List snap packages"
      ansible.builtin.shell: |
        for i in `snap list | awk '!/Name/{print $1}'`;do
          echo $i;
        done
      changed_when: false
      register: "snap_packages"

    - name: "Remove snap packages"
      ansible.builtin.command:
        cmd: "snap remove {{ item }}"
      with_items: "{{ snap_packages.stdout_lines }}"
      register: "snap_remove_output"
      changed_when: "'removed' in snap_remove_output.stdout"
  rescue:
    - name: "Check number of retries and fail if greater that 3"
      ansible.builtin.fail:
        msg: "Maximum retries of grouped tasks reached"
      when: "retry_count | int == 3"

    - name: "Printing retry message"
      ansible.builtin.debug:
        msg: "Removing snap package failed, let's give it another shot"

    - name: "Retrying deletion"
      ansible.builtin.include_tasks: "remove-snap-packages.yaml"
