---
- name: "Add repository"
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: "present"
    update_cache: true
  with_items: "{{ additional_repositories }}"

- name: "Install requirement packages"
  ansible.builtin.apt:
    name: "{{ install_packages }}"
    state: "present"
