---
- name: "Update DNS server"
  replace:
    path: "/etc/systemd/resolved.conf"
    regexp: "^#DNS="
    replace: "DNS=8.8.8.8 8.8.4.4"
  notify: "restart systemd-resolved"

- name: "Update NTP server"
  replace:
    path: "/etc/systemd/timesyncd.conf"
    regexp: "^#NTP="
    replace: "NTP=ntp1.jst.mfeed.ad.jp ntp2.jst.mfeed.ad.jp ntp3.jst.mfeed.ad.jp"
  notify: "restart systemd-timesyncd"

- name: "Set timezone to Asia/Tokyo"
  timezone:
    name: "Asia/Tokyo"

