---
- name: "Check installed asdf plugins"
  ansible.builtin.command:
    cmd: "{{ asdf_bin }} plugin list"
  register: "asdf_plugin_list"
  changed_when: false

- name: "Install asdf plugin for {{ plugin_name }}"
  ansible.builtin.command:
    cmd: "{{ asdf_bin }} plugin add {{ plugin_name }} {{ plugin_repository | default('') }}"
  when: "plugin_name not in asdf_plugin_list.stdout.splitlines()"
  register: "asdf_plugin_install"
  changed_when: "asdf_plugin_install.rc == 0"
