---
- name: "Install asdf"
  community.general.homebrew:
    name: "asdf"
    state: "present"
    update_homebrew: true

- name: "Add to path"
  ansible.builtin.blockinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    block: |
      export ASDF_DATA_DIR="$HOME/.asdf"
      export PATH="$ASDF_DATA_DIR/shims:$PATH"
    marker: "# {mark} ASDF SETUP"
    create: true
    prepend_newline: true
    mode: "0644"

- name: "Update all asdf plugins"
  ansible.builtin.command:
    cmd: "{{ asdf_bin }} plugin update --all"
