---
- name: "Check if homebrew is already installed"
  ansible.builtin.stat:
    path: "{{ homebrew_bin }}"
  register: "brew_installed"

- name: "Install homebrew section"
  when: "not brew_installed.stat.exists"
  block:
    - name: "Download installation script"
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
        dest: "{{ brew_install_script_path }}"
        mode: "0755"

    - name: "Run homebrew installer"
      ansible.builtin.command:
        cmd: "{{ brew_install_script_path }}"
      environment:
        NONINTERACTIVE: "1"
      changed_when: true

- name: "Configure homebrew"
  ansible.builtin.blockinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    block: |
      eval "$({{ homebrew_bin }} shellenv)"
    marker: "# {mark} HOMEBREW SETUP"
    create: true
    prepend_newline: true
    mode: "0644"

- name: "Upgrade all packages"
  community.general.homebrew:
    update_homebrew: true
    upgrade_all: true

- name: "Install gcc"
  community.general.homebrew:
    name: "gcc"
    state: "present"
