---
- name: "Install mise"
  community.general.homebrew:
    name: "mise"
    state: "present"

- name: "Add to path(.bash_profile)"
  ansible.builtin.blockinfile:
    path: "/home/{{ ansible_user }}/.bash_profile"
    block: |
      if [ -z "$MISE_INITIALIZED" ]; then
        export MISE_INITIALIZED=1
        eval "$({{ brew_package_dir }}/mise activate bash)"
      fi
    marker: "# {mark} ASDF MISE"
    create: true
    prepend_newline: true
    mode: "0644"

- name: "Add to path(.bashrc)"
  ansible.builtin.blockinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    block: |
      if [ -z "$MISE_INITIALIZED" ]; then
        export MISE_INITIALIZED=1
        eval "$({{ brew_package_dir }}/mise activate bash)"
      fi
    marker: "# {mark} ASDF MISE"
    create: true
    prepend_newline: true
    mode: "0644"
