---
- name: "Install mise"
  community.general.homebrew:
    name: "mise"
    state: "present"

- name: "Add to path(.zprofile)"
  ansible.builtin.blockinfile:
    path: "/home/{{ ansible_user }}/.zprofile"
    block: |
      eval "$({{ brew_package_dir }}/mise activate bash)"
    marker: "# {mark} MISE SETUP"
    create: true
    prepend_newline: true
    mode: "0644"
