---
- name: "Install AWS utils"
  community.general.homebrew:
    name:
      - "awscli"
      - "awscli-local"
      - "aws-sam-cli"
    state: "present"

- name: "Install aws-cdk"
  ansible.builtin.command:
    cmd: "{{ mise_shims }}/npm install -g aws-cdk@latest aws-cdk-local@latest"
  environment:
    PATH: "{{ brew_package_dir }}:{{ ansible_env.PATH }}"
  register: "npm_installation_result"
  changed_when: false
