---
- name: "Install vim"
  community.general.homebrew:
    name: "vim"
    state: "present"

- name: "Create .vim directory"
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.vim/autoload"
    state: "directory"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: "Install vim-plug for Vim"
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "/home/{{ ansible_user }}/.vim/autoload/plug.vim"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: "Ensure .vimrc has Plug section"
  ansible.builtin.blockinfile:
    path: "/home/{{ ansible_user }}/.vimrc"
    block: |
      set belloff=all

      hi Comment ctermfg=gray

      call plug#begin('~/.vim/plugged')

      Plug 'tpope/vim-sensible'
      Plug 'whatyouhide/vim-gotham'
      Plug 'obcat/vim-hitspop'
      Plug 'tpope/vim-surround'
      Plug 'tpope/vim-commentary'
      Plug 'gosukiwi/vim-smartpairs'
      Plug 'dominikduda/vim_current_word'
      Plug 'ntpeters/vim-better-whitespace'
      Plug 'ConradIrwin/vim-bracketed-paste'
      Plug 'skanehira/denops-translate.vim'
      Plug 'obcat/vim-sclow'
      Plug 'luochen1990/rainbow'
      Plug 'liuchengxu/vim-which-key'
      Plug 'psliwka/vim-smoothie'
      Plug 'simeji/winresizer'
      Plug 'preservim/vim-markdown'
      Plug 'i9wa4/vim-markdown-number-header'
      Plug 'mattn/vim-maketable'
      Plug 'iamcco/markdown-preview.nvim'
      Plug 'preservim/nerdtree'

      call plug#end()
    marker: "\" {mark} VIM-PLUG SETUP"
    create: true
    prepend_newline: true
    mode: "0644"

- name: "Run :PlugInstall in Vim"
  ansible.builtin.shell: |
    vim +PlugInstall +qall
  args:
    executable: "/bin/bash"
