---
- name: "Install mise plugin for java latest versions"
  ansible.builtin.include_tasks: "mise-versions.yaml"
  vars:
    plugin_name: "java"
    plugin_lib_version: "openjdk-21"
    current_version: true

- name: "Install mise plugin for java legacy versions"
  ansible.builtin.include_tasks: "mise-versions.yaml"
  vars:
    plugin_name: "java"
    plugin_lib_version: "{{ item }}"
    current_version: false
  loop:
    - "openjdk-17"
    - "openjdk-11"
    - "corretto-8"

- name: "Install JVM build-tools"
  community.general.homebrew:
    name:
      - "gradle"
      - "maven"
      - "kotlin"
    state: "present"

- name: "Uninstall managed openjdk"
  community.general.homebrew:
    name:
      - "openjdk"
    state: "absent"
    install_options: "ignore-dependencies"
