---
- name: "Install kubernetes utils"
  community.general.homebrew:
    name:
      - "kubernetes-cli"
      - "helm"
      - "helmfile"
      - "fluxcd/tap/flux"
    state: "present"
    update_homebrew: true
