---
- name: "Ensure .ssh directory exists"
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.ssh"
    mode: "0700"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: "directory"

- name: "Create private key file"
  ansible.builtin.copy:
    dest: "/home/{{ ansible_user }}/.ssh/{{ item.key_file }}"
    content: "{{ item.private_key }}"
    mode: "0600"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    force: true
  loop: "{{ ssh_configs }}"

- name: "Configure SSH config"
  ansible.builtin.template:
    src: "ssh_config.j2"
    dest: "/home/{{ ansible_user }}/.ssh/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
