---
- name: "Install golang & third party libs"
  community.general.homebrew:
    name:
      - "go"
      - "gofumpt"
      - "golangci-lint"
      - "gotestsum"
      - "skeema"
    state: "present"

- name: "Add golang to path"
  ansible.builtin.blockinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    block: |
      export PATH="$({{ go_bin }} env GOPATH)/bin:$PATH"
    marker: "# {mark} GO SETUP"
    create: true
    prepend_newline: true
    mode: "0644"

- name: "Install golang modules"
  ansible.builtin.command:
    cmd: "{{ go_bin }} install {{ item }}"
  loop:
    - "golang.org/x/tools/cmd/godoc@latest"
