---
- name: "Install mise plugin latest versions"
  ansible.builtin.include_tasks: "mise-versions.yaml"
  vars:
    plugin_name: "node"
    plugin_lib_version: "22"
    current_version: true

- name: "Install mise plugin for Node.js library legacy versions"
  ansible.builtin.include_tasks: "mise-versions.yaml"
  vars:
    plugin_name: "node"
    plugin_lib_version: "{{ item }}"
    current_version: false
  loop:
    - "20"
    - "18"
    - "16"
    - "14"
    - "12"
    - "10"
    - "8"

- name: "Enable corepack"
  ansible.builtin.command:
    cmd: "{{ mise_shims }}/corepack enable"
  register: "corepack_enabled"
  changed_when: false

- name: "Install node package-manager"
  community.general.homebrew:
    name: "pnpm"
    state: "present"
