---
- name: "Install python packages"
  community.general.homebrew:
    name:
      - "python@3.13"
      - "python@3.12"
      - "python@3.11"
      - "python@3.10"
      - "python@3.9"
      - "poetry"
    state: "present"
