---
- name: "Configure git"
  community.general.git_config:
    scope: "global"
    name: "{{ item.name }}"
    value: "{{ item.value }}"
  loop: "{{ git_configs }}"

- name: "Install vcs utils"
  community.general.homebrew:
    name:
      - "gh"
      - "act"
      - "action-validator"
      - "actionlint"
    state: "present"
