---
- name: "Added repositories"
  community.general.homebrew_tap:
    name:
      - "hashicorp/tap"
    state: "present"

- name: "Install dev utils"
  community.general.homebrew:
    name:
      - "hashicorp/tap/terraform"
      - "yq"
      - "shellcheck"
      - "direnv"
    state: "present"
