---
- name: "Install asdf plugins"
  ansible.builtin.include_tasks: "asdf-plugin.yaml"
  vars:
    plugin_name: "{{ item.plugin_name }}"
    plugin_repository: "{{ item.plugin_repository }}"
  loop:
    - plugin_name: "java"
      plugin_repository: "https://github.com/halcyon/asdf-java.git"

- name: "Install asdf plugin latest versions"
  ansible.builtin.include_tasks: "asdf-versions.yaml"
  vars:
    plugin_name: "{{ item.plugin_name }}"
    plugin_lib_version: "{{ item.plugin_lib_version }}"
    current_version: true
  loop:
    - plugin_name: "java"
      plugin_lib_version: "{{ java_latest_lts_version }}"

- name: "Install asdf plugin for java library legacy versions"
  ansible.builtin.include_tasks: "asdf-versions.yaml"
  vars:
    plugin_name: "java"
    plugin_lib_version: "{{ item }}"
    current_version: false
  loop: "{{ java_legacy_lts_versions }}"

- name: "Install JVM build-tools"
  community.general.homebrew:
    name:
      - "gradle"
      - "maven"
    state: "present"
