---
tmp_dir: "/tmp"
install_dir: "/usr/local/bin"

##################################################################
# homebrew
##################################################################
brew_install_script_path: "{{ tmp_dir }}/brew_install.sh"
homebrew_bin: "/home/linuxbrew/.linuxbrew/bin/brew"
brew_package_dir: "/home/linuxbrew/.linuxbrew/bin"
