---
- name: "Download act_Linux_arm64.tar.gz"
  ansible.builtin.get_url:
    url: "https://github.com/nektos/act/releases/latest/download/act_Linux_arm64.tar.gz"
    dest: "{{ tmp_dir }}/act_Linux_arm64.tar.gz"
    mode: "0644"

- name: "Extract act_Linux_arm64.tar.gz"
  ansible.builtin.unarchive:
    src: "{{ tmp_dir }}/act_Linux_arm64.tar.gz"
    dest: "{{ tmp_dir }}"

- name: "Move act binary to {{ install_dir }}"
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/act"
    dest: "{{ install_dir }}/act"
    owner: "root"
    group: "root"
    mode: "0755"
  become: true

- name: "Clean up temporary directory"
  ansible.builtin.file:
    path: "{{ tmp_dir }}/act_Linux_arm64.tar.gz"
    state: "absent"
