---
- name: "Restart systemd-resolved"
  ansible.builtin.service:
    name: "systemd-resolved"
    state: "restarted"

- name: "Restart systemd-timesyncd"
  ansible.builtin.service:
    name: "systemd-timesyncd"
    state: "restarted"
