---
name: "on-pull-request"

on:
  pull_request:

jobs:
  check-shell:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10

    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4"

      - name: "Check with shellcheck"
        uses: "reviewdog/action-shellcheck@v1"
        with:
          level: "warning"
